
[user_info]
author = "Perri van den Berg, Amber van den Broek, Dirck van den Ende"
team = "Rain Worms"
university = "Leiden University"

[document]
doctitle = "Reference Document"
enabled_sections = []
