// Returns the number generated by the Chinese
// remainder theorem, using the extended euclidean
// algorithm. Inputs are numbers a and b with modulo
// constants n and m. Returns x
ll crt(ll a, ll b, ll n, ll m) {
    ll s, t;
    euclidGcd(n, m, s, t);
    // Might have to change this if the numbers get too
    // large
    ll res = (a * m * t + b * n * s) % (n * m);
    if (res < 0)
        res += n * m;
    return res;
}