name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pygments
        run: sudo apt-get install python3-pygments
      - name: Install minted
        run: sudo apt-get install texlive-latex-extra 
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Programming Competition Reference
          path: reference.pdf
